#!/bin/bash

# Constants and Configuration
# ---------------------------

source config.sh

SCRIPT_DIRECTORY="$(dirname "$(realpath "$0")")"
KORE_RUNTIME_DIRECTORY="$SCRIPT_DIRECTORY/runtime/kore"


# ANSI color codes
# ----------------
RESET='\033[0m'
RED='\033[1m\033[31m'
BLUE='\033[1m\033[34m'


# Functions
# ---------

# Function to check if the container is running.
check_container_running() {
  if podman inspect --format "{{.State.Running}}" "$CONTAINER_NAME" 2>/dev/null | grep -q "true"; then
    return 0  # Container is running
  else
    return 1  # Container is not running
  fi
}

# Function to start the container.
start_container() {
  echo "Starting the container '$CONTAINER_NAME'..."
  if podman start "$CONTAINER_NAME"; then
    echo "Container '$CONTAINER_NAME' started successfully."
  else
    echo "Failed to start container '$CONTAINER_NAME'."
    exit 1
  fi
}


# Main Script Logic
# -----------------

# Notify the user about the deletion process.
echo "You are about to delete the container with name: $CONTAINER_NAME"

# Verify that the container should really be deleted.
echo -n "Are you sure you want to proceed with the deletion? (y/yes or n/no) [default: no]: "
read -r confirm
confirm=${confirm:-no}

# Check the user's confirmation.
while true; do
  case "$confirm" in
    [Yy]|[Yy][Ee][Ss])
      echo "Continuing with deletion process."
      echo "This process will involve multiple questions to determine how the deletion should be executed."
      echo ""
      break
      ;;
    [Nn]|[Nn][Oo])
      echo "Deletion aborted. No changes were made. Exiting script."
      exit 0
      ;;
    *)
      echo "Invalid response. Please enter 'yes' or 'no'."
      ;;
  esac
done

# Check how the data inside the container shall be handled.
echo "Various files will have accumulated over the lifetime of the container. The focus of this script is on the home directories of students, lecturers and grader users, the Exchange directory of nbgrader as well as LTI related files (autogenerated_services.py, instructors.json, lti_USERNAME.json)."
echo -e "${RED}You are responsible for backing up all other files and directories yourself before proceeding with the deletion.${RESET}"

# Check if the user made backed up all necessary files/directories.
echo -n "Have you backed up all the necessary files and directories? (y/yes or n/no) [default: no]: "
read -r confirm
confirm=${confirm:-no}

while true; do
  case "$confirm" in
    [Yy]|[Yy][Ee][Ss])
      break
      ;;
    [Nn]|[Nn][Oo])
      echo "Deletion aborted. No changes were made. Exiting script."
      exit 0
      ;;
    *)
      echo "Invalid response. Please enter 'yes' or 'no'."
      ;;
  esac
done

# Check if the container is running. Otherwise output a prompt for confirmation that the container needs to be started.
if check_container_running; then
  echo "Container '$CONTAINER_NAME' is already running. Proceeding ..."
else
  echo -e "The container '$CONTAINER_NAME' needs to be running. ${RED}This will open the connection/port and the container will be accessible until the deletion finished.${RESET}"
  read -r -p "Do you want to start it now? (y/yes or n/no) [default: no]: " confirm
  confirm=${confirm:-no}

  while true; do
    case "$confirm" in
      [Yy]|[Yy][Ee][Ss])
        start_container
        break
        ;;
      [Nn]|[Nn][Oo])
        echo "Container '$CONTAINER_NAME' will not be started."
        exit 0
        ;;
      *)
        echo "Invalid input. Please enter 'yes' or 'no'."
        ;;
    esac
  done
fi

# Ask the user how to handle the user home directories and the grader user home directories.
echo "Please decide how the directories and files of users (students and lecturers) and grader users as well as the files in the nbgrader exchange directory shall be treated."
echo "You may decide between the 'leave' and the 'remove' option."
echo -e "${BLUE}'leave'${RESET}  - This will change the permissions of all directories and files."
echo "           The home directories and the exchange directory may be found inside the runtime folder."
echo "           This is the safe option and also the default."
echo -e "${BLUE}'remove'${RESET} - This will delete the directories and all of there content completely."
echo "           This is the permanent option and should be used with caution."
echo "Note: LTI related files will be deleted regardless of your decision due to the error and fail potential if not removed, while trying to re-initialize the container."
echo ""

echo -n "How do you want to process with the directories? (l/leave or r/remove) [default: leave]: "
read -r decision
decision=${decision:-leave}

# Perform permission change or deletion for directories based on decision.
while true; do
  case "$decision" in
    [Ll]|[Ll][Ee][Aa][Vv][Ee])
      echo "Changing ownership & permission of home directories."
      podman exec -it "$CONTAINER_NAME" bash -c "chown -R root:root \"$USER_HOME_ROOT\" && chmod -R ug+rwX \"$USER_HOME_ROOT\""
      status=$?
      if [ $status -ne 0 ]; then
        echo "Error: Failed to change permission on at least one folder or file under $USER_HOME_ROOT."
        exit 1
      fi

      podman exec -it "$CONTAINER_NAME" bash -c "chown -R root:root \"$GRADER_HOME_ROOT\" && chmod -R ug+rwX \"$GRADER_HOME_ROOT\""
      status=$?
      if [ $status -ne 0 ]; then
        echo "Error: Failed to change permission on at least one folder or file under $GRADER_HOME_ROOT."
        exit 1
      fi

      podman exec -it "$CONTAINER_NAME" bash -c "chown -R root:root \"$NBGRADER_EXCHANGE_ROOT\" && chmod -R ug+rwX \"$NBGRADER_EXCHANGE_ROOT\""
      status=$?
      if [ $status -ne 0 ]; then
        echo "Error: Failed to change permission on at least one folder or file under $NBGRADER_EXCHANGE_ROOT."
        exit 1
      fi
      break
      ;;
    [Rr]|[Rr][Ee][Mm][Oo][Vv][Ee])
      echo "Removing home directories."
      podman exec -it "$CONTAINER_NAME" bash -c "find $USER_HOME_ROOT -mindepth 1 -delete"
      status=$?
      if [ $status -ne 0 ]; then
        echo "Error: Failed to remove all folders and files under $USER_HOME_ROOT."
        exit 1
      fi

      podman exec -it "$CONTAINER_NAME" bash -c "find $GRADER_HOME_ROOT -mindepth 1 -delete"
      status=$?
      if [ $status -ne 0 ]; then
        echo "Error: Failed to remove all folders and files under $GRADER_HOME_ROOT."
        exit 1
      fi

      podman exec -it "$CONTAINER_NAME" bash -c "find $NBGRADER_EXCHANGE_ROOT -mindepth 1 -delete"
      status=$?
      if [ $status -ne 0 ]; then
        echo "Error: Failed to remove all folders and files under $NBGRADER_EXCHANGE_ROOT."
        exit 1
      fi
      break
      ;;
    *)
      echo "Invalid response. Please enter 'leave' or 'remove'."
      ;;
  esac
done

# Delete LTI related files if they exist.
if [ -d "$KORE_RUNTIME_DIRECTORY" ] && [ "$(ls -A "$KORE_RUNTIME_DIRECTORY")" ]; then
  find "$KORE_RUNTIME_DIRECTORY" -mindepth 1 ! -name ".*" -delete
fi

# Stopping service.
echo "Stopping and removing service."
service_name="container-$CONTAINER_NAME"
if systemctl --user list-units | grep -q "$service_name"; then
  systemctl --user stop "$service_name"
  systemctl --user disable "$service_name"
fi


# Cleanup and Exit
# ----------------

rm ~/.config/systemd/user/container-"$CONTAINER_NAME".service

podman rm "$CONTAINER_NAME"
echo "Deletion of container finished successfully!"