#!/usr/bin/env python3

import argparse
import subprocess

def shell(cmd):
    '''
    Run a shell command and return its output.

    Parameters
    ----------
    cmd : list[str]
        Command to execute. First item is command. Others are arguments.

    Returns
    -------
    list[str]
        List of lines returned on stdout.
    '''

    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.stdout.split('\n')


def subcmd_list(args):

    print('list')


def subcmd_build(args):

    print('build')


def main():

    # intialize argument parser
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(
        title='subcommands',
        description='build, list ("ananke SUBCOMMAND -h" for details)'
    )

    # subparser for build command
    parser_build = subparsers.add_parser('build', help='build an image')
    parser_build.add_argument('-n', '--name', help='name of built image')
    parser_build.add_argument('image_def', metavar='IMAGE_DEFINITION_DIR', help='directory with image definition')
    parser_build.set_defaults(func=subcmd_build)

    # subparser for list command
    parser_list = subparsers.add_parser('list', help='list images and containers')
    parser_list.set_defaults(func=subcmd_list)

    # execute command
    args = parser.parse_args()
    if 'func' in args:
        args.func(args)
    else:
        parser.print_usage()


if __name__ == '__main__':
    main()
