from nbgrader.auth import JupyterHubAuthPlugin

c = get_config()

c.Exchange.path_includes_course = True
c.Authenticator.plugin_class = JupyterHubAuthPlugin
c.Exchange.root = '/opt/nbgrader_exchange'
c.NbGrader.logfile = '/opt/conda/envs/jhub/share/jupyter/nbgrader.log' 

# course ID to course title mapping (autogenerated, do not modify)
c.NbGrader.course_titles = {}
