import logging

logging.basicConfig(
    level=logging.DEBUG,
    format='[%(levelname)1.1s %(asctime)s.%(msecs)03d %(module)s:%(lineno)d] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)


class KoreError(Exception):
    """ Base class for kore related errors. """
    pass


class AutogeneratedFileError(KoreError):
    """ Autogenerated file related error. """

    def __init__(self):
        self.message = 'An error occurred while interacting with the autogenerated configuration file.'
        logging.error(self.message)
        super().__init__(self.message)


class ConfigFileError(KoreError):
    """ Config file related error. """

    def __init__(self):
        self.message = 'An error occurred while interacting with the config file.'
        logging.error(self.message)
        super().__init__(self.message)


class InfoFileError(KoreError):
    """ Info file related error. """

    def __init__(self):
        self.message = 'An error occurred while interacting with the info file of the user.'
        logging.error(self.message)
        super().__init__(self.message)


class CleanUpError(KoreError):
    """ Info file related error. """

    def __init__(self):
        self.message = 'An error occurred while interacting with the gradebook.db file.'
        logging.error(self.message)
        super().__init__(self.message)


class ActivePathsError(KoreError):
    """ Error related to path of active course. """

    def __init__(self):
        self.message = 'An error occurred while generating path list of current course.'
        logging.error(self.message)
        super().__init__(self.message)


class UniqueNamesError(KoreError):
    """ Error related to unique name generation. """

    def __init__(self):
        self.message = 'An error occurred while generating unique names.'
        logging.error(self.message)
        super().__init__(self.message)
