FROM docker.io/library/debian@sha256:3615a749858a1cba49b408fb49c37093db813321355a9ab7c1f9f4836341e9db

ARG DEBIAN_FRONTEND=noninteractive
ARG TERM=linux

ARG JUPYTERHUB_VERSION=5.4.6
ARG JUPYTERLAB_VERSION=4.5.7
ARG NOTEBOOK_VERSION=7.5.6
ARG LTIAUTHENTICATOR_VERSION=1.6.3
ARG SYSTEMDSPAWNER_VERSION=1.0.2
ARG PYTHON_VERSION=3.14.4

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    git \
    gpg \
    htop \
    less \
    libnss-systemd \
    locales \
    nano \
    systemd \
    systemd-container && \
    rm -rf /var/lib/apt/lists/*

# install conda
RUN curl -L -o "/opt/miniforge.sh" "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    chmod o+x /opt/miniforge.sh && \
    /opt/miniforge.sh -b -p /opt/conda

# create conda envs
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda create -n jhub -y; \
    conda create -n python3 -y; \
    conda clean -afy"

# install conda packages
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda activate jhub; \
    conda install -y \
    jupyterhub=$JUPYTERHUB_VERSION \
    jupyterlab=$JUPYTERLAB_VERSION \
    jupyterlab_execute_time \
    jupyter-resource-usage \
    nb_conda_kernels \
    notebook=$NOTEBOOK_VERSION \
    pycurl \
    python=$PYTHON_VERSION \
    pip; \
    conda clean -afy"

RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda activate python3; \
    conda install -y \
    ipykernel \
    python=$PYTHON_VERSION \
    pip; \
    conda clean -afy"

# install pip packages
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda activate jhub; \
    pip install --root-user-action=ignore \
    jupyterhub-idle-culler \
    jupyterhub-ltiauthenticator==$LTIAUTHENTICATOR_VERSION \
    jupyterhub-systemdspawner==$SYSTEMDSPAWNER_VERSION \
    nbgitpuller; \
    pip cache purge"

# fix nb_conda_kernels install (remove unused outdated config file),
# modify display name of python3 env's kernel,
# disable jhub env's kernel,
# update kernel list for JupyterLab
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    rm /opt/conda/envs/jhub/etc/jupyter/jupyter_config.json; \
    conda activate python3; \
    python -m ipykernel install --prefix=/opt/conda/envs/python3/ --display-name 'Python 3 (all users)'; \
    conda activate jhub; \
    jupyter kernelspec remove -y python3; \
    python -m nb_conda_kernels list --CondaKernelSpecManager.kernelspec_path='--sys-prefix' --CondaKernelSpecManager.name_format='{display_name}'"

# copy JupyterHub config files
COPY ./assets/jupyterhub_config.py /opt/conda/envs/jhub/etc/jupyterhub/jupyterhub_config.py
COPY ./assets/jupyter_config.py /opt/conda/envs/jhub/etc/jupyter/jupyter_config.py
COPY ./assets/jupyterhub.service /opt/conda/envs/jhub/etc/systemd/jupyterhub.service
RUN chmod a+r /opt/conda/envs/jhub/etc/jupyterhub/jupyterhub_config.py
RUN chmod a+r /opt/conda/envs/jhub/etc/jupyter/jupyter_config.py
RUN chmod a+r /opt/conda/envs/jhub/etc/systemd/jupyterhub.service

# create systemd service for JupyterHub
RUN ln -s /opt/conda/envs/jhub/etc/systemd/jupyterhub.service /etc/systemd/system/jupyterhub.service
RUN systemctl enable jupyterhub.service

# make python3 the default conda env for all terminals
RUN echo "PS1=\"\w$ \"" >> /etc/bash.bashrc && \
    echo "source /opt/conda/etc/profile.d/conda.sh" >> /etc/bash.bashrc && \
    echo "conda activate python3" >> /etc/bash.bashrc

# copy install scripts for optional python packages    
COPY ./assets/install /opt/install
RUN chmod 755 /opt/install
RUN chmod 644 /opt/install/*
RUN chmod 744 /opt/install/*.sh
    
# initialize user_data.json
WORKDIR /opt
RUN touch user_data.json && \
    echo "{}" >> user_data.json && \
    chmod 600 user_data.json

# copy boot script and create systemd service for boot script
COPY ./assets/boot.sh /opt/boot.sh
RUN chmod 700 /opt/boot.sh
COPY ./assets/boot_script.service /etc/systemd/system/boot_script.service
RUN systemctl enable boot_script.service

# disable root login (should be disabled by default, just to be sure...)
RUN passwd -l root

WORKDIR /

EXPOSE 8000

ENTRYPOINT ["/lib/systemd/systemd"]
