FROM ananke-base

# official nbgrader releases not used until https://github.com/jupyter/nbgrader/pull/1797 gets merged 
#ARG NBGRADER_VERSION=0.9.5

# install nbgrader and kore
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda activate jhub; \
    pip install --root-user-action=ignore git+https://github.com/jeflem/nbgrader.git@ananke_0.7; \
    pip install --root-user-action=ignore git+https://github.com/marcwit/kore-extension.git@ananke_0.5; \
    pip cache purge"
#    pip install --root-user-action=ignore git+https://github.com/jupyter/nbgrader.git@v$NBGRADER_VERSION"

# install additional packages
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda activate jhub; \
    conda install -y flask flask-session jwcrypto pycryptodome gunicorn; \
    conda clean -afy"

# copy config files
COPY ./assets/nbgrader_config.py /opt/conda/envs/jhub/etc/jupyter/nbgrader_config.py
RUN chmod a+r /opt/conda/envs/jhub/etc/jupyter/nbgrader_config.py

# nbgrader exchange directory
RUN mkdir /opt/nbgrader_exchange && \
    chmod 777 /opt/nbgrader_exchange

# set nbgrader_exchange permissions in boot script
# (permissions may be overwritten by mount at container creation)
RUN echo "chmod 777 /opt/nbgrader_exchange" >> /opt/boot.sh

# nbgrader log file
RUN touch /opt/conda/envs/jhub/share/jupyter/nbgrader.log && \
    chmod 666 /opt/conda/envs/jhub/share/jupyter/nbgrader.log

# set nbgrader.log permissions in boot script
# (permissions may be overwritten by mount at container creation)
RUN echo "chmod 666 /opt/conda/envs/jhub/share/jupyter/nbgrader.log" >> /opt/boot.sh

# nbgrader extensions
# (explicitly enabling server extensions is necessary for getting all config files
# in /opt/conda/envs/jhub/etc/jupyter/jupyter_server_config.d; those file's will
# later be copied to user home directories, which is necessary to circumvent problems
# with enabling server extensions on a per user basis)
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda activate jhub; \
    jupyter server extension disable --sys-prefix nbgrader.server_extensions.formgrader; \
    jupyter labextension disable --level=sys_prefix @jupyter/nbgrader:formgrader; \
    jupyter labextension lock --level=sys_prefix @jupyter/nbgrader:formgrader; \
    jupyter server extension disable --sys-prefix nbgrader.server_extensions.course_list; \
    jupyter labextension disable --level=sys_prefix @jupyter/nbgrader:course-list; \
    jupyter labextension lock --level=sys_prefix @jupyter/nbgrader:course-list; \
    jupyter labextension disable --level=sys_prefix @jupyter/nbgrader:create-assignment; \
    jupyter labextension lock --level=sys_prefix @jupyter/nbgrader:create-assignment; \
    jupyter server extension enable --sys-prefix nbgrader.server_extensions.assignment_list; \
    jupyter labextension enable --level=sys_prefix @jupyter/nbgrader:assignment-list; \
    jupyter server extension enable --sys-prefix nbgrader.server_extensions.validate_assignment; \
    jupyter labextension enable --level=sys_prefix @jupyter/nbgrader:validate-assignment"

# copy Kore
COPY ./assets/kore /opt/kore
RUN mkdir -p /opt/kore/runtime
RUN chmod -R go-rwx /opt/kore

# disable kore-extension globally
RUN bash -c "source /opt/conda/etc/profile.d/conda.sh; \
    conda activate jhub; \
    jupyter labextension disable --level=sys_prefix kore-extension; \
    jupyter labextension lock --level=sys_prefix kore-extension"

# extend boot script to create LTI keys
RUN echo "cd /opt/kore" >> /opt/boot.sh && \
    echo "mkdir -p keys" >> /opt/boot.sh && \
    echo "source /opt/conda/etc/profile.d/conda.sh" >> /opt/boot.sh && \
    echo "conda activate jhub" >> /opt/boot.sh && \
    echo "python misc/make_keys.py" >> /opt/boot.sh && \
    echo "chmod 600 keys/lti_key" >> /opt/boot.sh

# extend boot script to create Kore cookie secret
RUN echo "cd /opt/kore" >> /opt/boot.sh && \
    echo "openssl rand -hex 32 > cookie_secret" >> /opt/boot.sh && \
    echo "chmod 600 cookie_secret" >> /opt/boot.sh
    
WORKDIR /

EXPOSE 8000

ENTRYPOINT ["/lib/systemd/systemd"]