FROM docker.io/library/debian@sha256:3615a749858a1cba49b408fb49c37093db813321355a9ab7c1f9f4836341e9db

ARG DEBIAN_FRONTEND=noninteractive
ARG TERM=linux

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    cron \
    curl \
    gpg \
    less \
    libnss-systemd \
    locales \
    mariadb-server \
    nano \
    nginx \
    php-common \
    php-fpm \
    php-cli \
    php-ctype \
    php-curl \
    php-dom \
    php-gd \
    php-iconv \
    php-intl \
    php-mbstring \
    php-mysql \
    php-simplexml \
    php-xml \
    php-zip \
    systemd \
    systemd-container && \
    rm -rf /var/lib/apt/lists/*

# setup nginx
COPY ./assets/nginx_default /etc/nginx/sites-available/default

# setup PHP
RUN sed -i 's\;max_input_vars = 1000\max_input_vars = 5000\g' /etc/php/8.4/cli/php.ini && \
    sed -i 's\;max_input_vars = 1000\max_input_vars = 5000\g' /etc/php/8.4/fpm/php.ini

# download and unzip Moodle
RUN mkdir /opt/moodledata
RUN cd /var/www/html && \
    curl -o moodle.tgz https://packaging.moodle.org/stable502/moodle-5.2.tgz && \
    tar -xvzf moodle.tgz && \
    rm moodle.tgz && \
    chmod -R 755 /var/www/html/moodle
    
# make data base files accessible to all users
# (else, deleting the data base outside the container requires root privileges)
RUN chown -R mysql:mysql /var/lib/mysql && \
    chmod -R a+rwX /var/lib/mysql

# make root the owner of Moodle files (seems to be not the case after install?!)
# make Moodle files readable for non-root users (www-data!)
RUN chown -R root:root /var/www/html/moodle && \
    chmod -R a+r /var/www/html/moodle

# setup cron    
COPY ./assets/crontab /etc/crontab

# move all directories to be persisted to temporary location
# (boot script will copy those to mounted volumes at first boot)
#RUN mv /var/lib/mysql /var/lib/mysql_original
#RUN mv /opt/moodledata /opt/moodledata_original
#RUN mv /var/www/html/moodle /var/www/html/moodle_original
    
# copy boot script and create systemd service for boot script
COPY ./assets/boot.sh /opt/boot.sh
RUN chmod 700 /opt/boot.sh
COPY ./assets/boot_script.service /etc/systemd/system/boot_script.service
RUN systemctl enable boot_script.service

# disable root login (should be disabled by default, just to be sure...)
RUN passwd -l root

WORKDIR /

EXPOSE 80

ENTRYPOINT ["/lib/systemd/systemd"]
